"""PAAR codec subpackage."""
from __future__ import annotations
from .paar_manifest_codec import (
    REMOTE_HOST_PROTOCOL_NAME,
    REMOTE_HOST_PROTOCOL_VERSION,
    MAGIC0,
    MAGIC1,
    MAGIC2,
    MAGIC3,
    MAGIC4,
    MAGIC_BYTES,
    HEADER_PREFIX,
    MAX_MANIFEST_BYTES,
    MAX_FILES,
    MAX_FILE_SIZE,
    MAX_TOTAL_PAYLOAD,
    MAX_ARCHIVE_SIZE,
    MAX_PATH_BYTES,
    SAFE_INT_MAX,
    PAAR_ERRORS,
    PaarError,
    PaarFileEntry,
    PaarProtocolInfo,
    PaarManifest,
    PaarEncodeResult,
    PaarDecodeResult,
    PaarOk,
    PaarErr,
    PaarResult,
    encode_paar_manifest,
    decode_paar_manifest_header,
)
