// Compatibility exports; implementation lives with its feature owner.
export {
	type AgentSessionCreationOptions,
	AgentSessionRuntime,
	type AgentSessionRuntimeConfig,
	type AgentSessionRuntimeDiagnostic,
	type AgentSessionRuntimeDisposeOptions,
	type AgentSessionRuntimeKind,
	type AgentSessionRuntimeMetadata,
	type AgentSessionServices,
	type CreateAgentSessionFromServicesOptions,
	type CreateAgentSessionOptions,
	type CreateAgentSessionResult,
	type CreateAgentSessionRuntimeFactory,
	type CreateAgentSessionRuntimeResult,
	type CreateAgentSessionServicesOptions,
	type CreateRlmSubagentRuntimeOptions,
	createAgentSession,
	createAgentSessionFromServices,
	createAgentSessionRuntime,
	createAgentSessionServices,
	createBashTool,
	createEditTool,
	createIpythonTool,
	type ExtensionAPI,
	type ExtensionCommandContext,
	type ExtensionContext,
	type ExtensionFactory,
	type PromptTemplate,
	type RlmSubagentRuntime,
	SessionImportFileNotFoundError,
	type Skill,
	type SlashCommandInfo,
	type SlashCommandSource,
	type SubagentRuntimeHost,
	type Tool,
	type ToolDefinition,
	withFileMutationQueue,
} from "../sdk/index.js";
