export interface TelemetryPropertyRule {
	kind: string;
	values?: readonly string[];
	fallback?: string;
	max?: number;
	integer?: boolean;
	nullable?: boolean;
}
export interface TelemetryEventRule {
	legacy: boolean;
	required: readonly string[];
	properties: Readonly<Record<string, TelemetryPropertyRule>>;
	legacy_properties?: readonly string[];
}

export const TELEMETRY_CONTRACT: {
	schema_version: number;
	schema_revision: number;
	diagnostic_messages: Readonly<Record<string, string>>;
	events: Readonly<Record<string, TelemetryEventRule>>;
} = {
	schema_version: 2,
	schema_revision: 1,
	events: {
		"agent started": {
			legacy: true,
			required: ["version", "os_family", "architecture", "install_method", "execution_mode", "session_id"],
			properties: {
				version: {
					kind: "version",
				},
				os_family: {
					kind: "enum",
					values: [
						"aix",
						"android",
						"darwin",
						"freebsd",
						"haiku",
						"linux",
						"netbsd",
						"openbsd",
						"sunos",
						"win32",
						"cygwin",
						"unknown",
					],
					fallback: "unknown",
				},
				architecture: {
					kind: "enum",
					values: [
						"arm",
						"arm64",
						"ia32",
						"loong64",
						"mips",
						"mipsel",
						"ppc",
						"ppc64",
						"riscv64",
						"s390",
						"s390x",
						"x64",
						"unknown",
					],
					fallback: "unknown",
				},
				install_method: {
					kind: "enum",
					values: ["bun-binary", "homebrew", "npm", "pnpm", "yarn", "bun", "unknown"],
					fallback: "unknown",
				},
				execution_mode: {
					kind: "enum",
					values: ["interactive", "print", "json", "rpc", "acp", "unknown"],
					fallback: "unknown",
				},
				session_id: {
					kind: "uuid",
				},
				schema_revision: {
					kind: "number",
					max: 10000,
					integer: true,
				},
				build_channel: {
					kind: "enum",
					values: ["release", "prerelease", "development", "unknown"],
					fallback: "unknown",
				},
				workload_origin: {
					kind: "enum",
					values: ["interactive", "automated", "internal", "test", "unknown"],
					fallback: "unknown",
				},
				run_id: {
					kind: "uuid",
				},
				client_session_id: {
					kind: "uuid",
				},
				onboarding_id: {
					kind: "uuid",
				},
				run_index: {
					kind: "number",
					max: 1000000,
					integer: true,
				},
				elapsed_since_onboarding_ms: {
					kind: "number",
					max: 31536000000,
					integer: true,
					nullable: true,
				},
				provider_category: {
					kind: "enum",
					values: [
						"anthropic",
						"openai",
						"google",
						"prime",
						"openrouter",
						"bedrock",
						"vertex",
						"mistral",
						"groq",
						"xai",
						"custom",
						"unknown",
					],
					fallback: "custom",
				},
				model_category: {
					kind: "enum",
					values: [
						"claude",
						"gpt",
						"o1",
						"o3",
						"o4",
						"gemini",
						"glm",
						"kimi",
						"qwen",
						"deepseek",
						"llama",
						"mistral",
						"custom",
						"unknown",
					],
					fallback: "custom",
				},
			},
			legacy_properties: ["version", "os_family", "architecture", "install_method", "execution_mode", "session_id"],
		},
		"onboarding completed": {
			legacy: true,
			required: [
				"version",
				"os_family",
				"architecture",
				"install_method",
				"execution_mode",
				"duration_ms",
				"outcome",
				"auth_category",
				"provider_category",
			],
			properties: {
				version: {
					kind: "version",
				},
				os_family: {
					kind: "enum",
					values: [
						"aix",
						"android",
						"darwin",
						"freebsd",
						"haiku",
						"linux",
						"netbsd",
						"openbsd",
						"sunos",
						"win32",
						"cygwin",
						"unknown",
					],
					fallback: "unknown",
				},
				architecture: {
					kind: "enum",
					values: [
						"arm",
						"arm64",
						"ia32",
						"loong64",
						"mips",
						"mipsel",
						"ppc",
						"ppc64",
						"riscv64",
						"s390",
						"s390x",
						"x64",
						"unknown",
					],
					fallback: "unknown",
				},
				install_method: {
					kind: "enum",
					values: ["bun-binary", "homebrew", "npm", "pnpm", "yarn", "bun", "unknown"],
					fallback: "unknown",
				},
				execution_mode: {
					kind: "enum",
					values: ["interactive", "print", "json", "rpc", "acp", "unknown"],
					fallback: "unknown",
				},
				duration_ms: {
					kind: "number",
					max: 31536000000,
					integer: true,
					nullable: true,
				},
				outcome: {
					kind: "enum",
					values: ["success", "error", "aborted"],
				},
				auth_category: {
					kind: "enum",
					values: [
						"oauth",
						"api_key",
						"runtime_api_key",
						"environment",
						"prime_cli",
						"models_json",
						"fallback",
						"stale",
						"stored",
						"none",
					],
					fallback: "none",
				},
				provider_category: {
					kind: "enum",
					values: [
						"anthropic",
						"openai",
						"google",
						"prime",
						"openrouter",
						"bedrock",
						"vertex",
						"mistral",
						"groq",
						"xai",
						"custom",
						"unknown",
					],
					fallback: "custom",
				},
				schema_revision: {
					kind: "number",
					max: 10000,
					integer: true,
				},
				build_channel: {
					kind: "enum",
					values: ["release", "prerelease", "development", "unknown"],
					fallback: "unknown",
				},
				workload_origin: {
					kind: "enum",
					values: ["interactive", "automated", "internal", "test", "unknown"],
					fallback: "unknown",
				},
				session_id: {
					kind: "uuid",
				},
				run_id: {
					kind: "uuid",
				},
				client_session_id: {
					kind: "uuid",
				},
				onboarding_id: {
					kind: "uuid",
				},
				run_index: {
					kind: "number",
					max: 1000000,
					integer: true,
				},
				elapsed_since_onboarding_ms: {
					kind: "number",
					max: 31536000000,
					integer: true,
					nullable: true,
				},
				model_category: {
					kind: "enum",
					values: [
						"claude",
						"gpt",
						"o1",
						"o3",
						"o4",
						"gemini",
						"glm",
						"kimi",
						"qwen",
						"deepseek",
						"llama",
						"mistral",
						"custom",
						"unknown",
					],
					fallback: "custom",
				},
			},
			legacy_properties: [
				"version",
				"os_family",
				"architecture",
				"install_method",
				"execution_mode",
				"duration_ms",
				"outcome",
				"auth_category",
				"provider_category",
			],
		},
		"agent command used": {
			legacy: true,
			required: ["version", "os_family", "architecture", "install_method", "execution_mode", "command_name"],
			properties: {
				version: {
					kind: "version",
				},
				os_family: {
					kind: "enum",
					values: [
						"aix",
						"android",
						"darwin",
						"freebsd",
						"haiku",
						"linux",
						"netbsd",
						"openbsd",
						"sunos",
						"win32",
						"cygwin",
						"unknown",
					],
					fallback: "unknown",
				},
				architecture: {
					kind: "enum",
					values: [
						"arm",
						"arm64",
						"ia32",
						"loong64",
						"mips",
						"mipsel",
						"ppc",
						"ppc64",
						"riscv64",
						"s390",
						"s390x",
						"x64",
						"unknown",
					],
					fallback: "unknown",
				},
				install_method: {
					kind: "enum",
					values: ["bun-binary", "homebrew", "npm", "pnpm", "yarn", "bun", "unknown"],
					fallback: "unknown",
				},
				execution_mode: {
					kind: "enum",
					values: ["interactive", "print", "json", "rpc", "acp", "unknown"],
					fallback: "unknown",
				},
				command_name: {
					kind: "enum",
					values: [
						"settings",
						"model",
						"effort",
						"fast",
						"scoped-models",
						"export",
						"import",
						"share",
						"copy",
						"btw",
						"name",
						"session",
						"system-prompt",
						"logs",
						"traces",
						"context",
						"changelog",
						"update",
						"hotkeys",
						"fork",
						"clone",
						"tree",
						"login",
						"logout",
						"mcp",
						"new",
						"compact",
						"refine",
						"goal",
						"autonomous",
						"rlm-max-depth",
						"heartbeat",
						"heartbeats",
						"reload",
						"fullscreen",
						"quit",
					],
				},
				schema_revision: {
					kind: "number",
					max: 10000,
					integer: true,
				},
				build_channel: {
					kind: "enum",
					values: ["release", "prerelease", "development", "unknown"],
					fallback: "unknown",
				},
				workload_origin: {
					kind: "enum",
					values: ["interactive", "automated", "internal", "test", "unknown"],
					fallback: "unknown",
				},
				session_id: {
					kind: "uuid",
				},
				run_id: {
					kind: "uuid",
				},
				client_session_id: {
					kind: "uuid",
				},
				onboarding_id: {
					kind: "uuid",
				},
				run_index: {
					kind: "number",
					max: 1000000,
					integer: true,
				},
				elapsed_since_onboarding_ms: {
					kind: "number",
					max: 31536000000,
					integer: true,
					nullable: true,
				},
				provider_category: {
					kind: "enum",
					values: [
						"anthropic",
						"openai",
						"google",
						"prime",
						"openrouter",
						"bedrock",
						"vertex",
						"mistral",
						"groq",
						"xai",
						"custom",
						"unknown",
					],
					fallback: "custom",
				},
				model_category: {
					kind: "enum",
					values: [
						"claude",
						"gpt",
						"o1",
						"o3",
						"o4",
						"gemini",
						"glm",
						"kimi",
						"qwen",
						"deepseek",
						"llama",
						"mistral",
						"custom",
						"unknown",
					],
					fallback: "custom",
				},
			},
			legacy_properties: [
				"version",
				"os_family",
				"architecture",
				"install_method",
				"execution_mode",
				"command_name",
			],
		},
		"agent run completed": {
			legacy: true,
			required: [
				"version",
				"os_family",
				"architecture",
				"install_method",
				"execution_mode",
				"session_id",
				"outcome",
				"duration_ms",
				"visible_ttft_ms",
				"first_model_event_ms",
				"model_latency_ms",
				"max_model_latency_ms",
				"model_call_count",
				"turn_count",
				"tool_call_count",
				"tool_error_count",
				"input_tokens",
				"output_tokens",
				"cache_read_tokens",
				"cache_write_tokens",
				"total_tokens",
				"compaction_count",
				"retry_count",
				"provider_category",
				"model_category",
				"error_category",
			],
			properties: {
				version: {
					kind: "version",
				},
				os_family: {
					kind: "enum",
					values: [
						"aix",
						"android",
						"darwin",
						"freebsd",
						"haiku",
						"linux",
						"netbsd",
						"openbsd",
						"sunos",
						"win32",
						"cygwin",
						"unknown",
					],
					fallback: "unknown",
				},
				architecture: {
					kind: "enum",
					values: [
						"arm",
						"arm64",
						"ia32",
						"loong64",
						"mips",
						"mipsel",
						"ppc",
						"ppc64",
						"riscv64",
						"s390",
						"s390x",
						"x64",
						"unknown",
					],
					fallback: "unknown",
				},
				install_method: {
					kind: "enum",
					values: ["bun-binary", "homebrew", "npm", "pnpm", "yarn", "bun", "unknown"],
					fallback: "unknown",
				},
				execution_mode: {
					kind: "enum",
					values: ["interactive", "print", "json", "rpc", "acp", "unknown"],
					fallback: "unknown",
				},
				session_id: {
					kind: "uuid",
				},
				outcome: {
					kind: "enum",
					values: ["success", "error", "aborted"],
				},
				duration_ms: {
					kind: "number",
					max: 31536000000,
					integer: true,
					nullable: true,
				},
				visible_ttft_ms: {
					kind: "number",
					max: 31536000000,
					integer: true,
					nullable: true,
				},
				first_model_event_ms: {
					kind: "number",
					max: 31536000000,
					integer: true,
					nullable: true,
				},
				model_latency_ms: {
					kind: "number",
					max: 31536000000,
					integer: true,
					nullable: true,
				},
				max_model_latency_ms: {
					kind: "number",
					max: 31536000000,
					integer: true,
					nullable: true,
				},
				model_call_count: {
					kind: "number",
					max: 1000000,
					integer: true,
				},
				turn_count: {
					kind: "number",
					max: 1000000,
					integer: true,
				},
				tool_call_count: {
					kind: "number",
					max: 1000000,
					integer: true,
				},
				tool_error_count: {
					kind: "number",
					max: 1000000,
					integer: true,
				},
				input_tokens: {
					kind: "number",
					max: 1000000000000,
					integer: true,
				},
				output_tokens: {
					kind: "number",
					max: 1000000000000,
					integer: true,
				},
				cache_read_tokens: {
					kind: "number",
					max: 1000000000000,
					integer: true,
				},
				cache_write_tokens: {
					kind: "number",
					max: 1000000000000,
					integer: true,
				},
				total_tokens: {
					kind: "number",
					max: 1000000000000,
					integer: true,
				},
				compaction_count: {
					kind: "number",
					max: 1000000,
					integer: true,
				},
				retry_count: {
					kind: "number",
					max: 1000000,
					integer: true,
				},
				provider_category: {
					kind: "enum",
					values: [
						"anthropic",
						"openai",
						"google",
						"prime",
						"openrouter",
						"bedrock",
						"vertex",
						"mistral",
						"groq",
						"xai",
						"custom",
						"unknown",
					],
					fallback: "custom",
				},
				model_category: {
					kind: "enum",
					values: [
						"claude",
						"gpt",
						"o1",
						"o3",
						"o4",
						"gemini",
						"glm",
						"kimi",
						"qwen",
						"deepseek",
						"llama",
						"mistral",
						"custom",
						"unknown",
					],
					fallback: "custom",
				},
				error_category: {
					kind: "enum",
					values: [
						"authentication",
						"rate_limit",
						"timeout",
						"context_limit",
						"network",
						"provider_unavailable",
						"other",
					],
					fallback: "other",
					nullable: true,
				},
				schema_revision: {
					kind: "number",
					max: 10000,
					integer: true,
				},
				build_channel: {
					kind: "enum",
					values: ["release", "prerelease", "development", "unknown"],
					fallback: "unknown",
				},
				workload_origin: {
					kind: "enum",
					values: ["interactive", "automated", "internal", "test", "unknown"],
					fallback: "unknown",
				},
				run_id: {
					kind: "uuid",
				},
				client_session_id: {
					kind: "uuid",
				},
				onboarding_id: {
					kind: "uuid",
				},
				run_index: {
					kind: "number",
					max: 1000000,
					integer: true,
				},
				elapsed_since_onboarding_ms: {
					kind: "number",
					max: 31536000000,
					integer: true,
					nullable: true,
				},
				terminal_outcome: {
					kind: "enum",
					values: ["success", "error", "cancelled", "shutdown_interrupted", "unknown"],
					fallback: "unknown",
				},
				first_status_ms: {
					kind: "number",
					max: 31536000000,
					integer: true,
					nullable: true,
				},
				first_reasoning_ms: {
					kind: "number",
					max: 31536000000,
					integer: true,
					nullable: true,
				},
				run_to_first_text_ms: {
					kind: "number",
					max: 31536000000,
					integer: true,
					nullable: true,
				},
				tool_duration_ms: {
					kind: "number",
					max: 31536000000,
					integer: true,
					nullable: true,
				},
				retry_wait_ms: {
					kind: "number",
					max: 31536000000,
					integer: true,
					nullable: true,
				},
				compaction_duration_ms: {
					kind: "number",
					max: 31536000000,
					integer: true,
					nullable: true,
				},
				max_stream_gap_ms: {
					kind: "number",
					max: 31536000000,
					integer: true,
					nullable: true,
				},
				error_subtype: {
					kind: "enum",
					values: [
						"credential_missing",
						"credential_invalid",
						"credential_expired",
						"authentication_rejected",
						"permission_denied",
						"model_access_denied",
						"insufficient_balance",
						"quota_exceeded",
						"rate_limited",
						"network_error",
						"timeout",
						"provider_unavailable",
						"refusal",
						"malformed_response",
						"context_limit",
						"configuration_error",
						"filesystem_error",
						"session_unavailable",
						"cancelled",
						"unknown",
					],
					fallback: "unknown",
				},
				usage_complete: {
					kind: "boolean",
				},
				estimated_cost_usd: {
					kind: "number",
					max: 1000000,
					nullable: true,
				},
				cost_revision: {
					kind: "number",
					max: 10000,
					integer: true,
				},
				stop_reason: {
					kind: "enum",
					values: ["stop", "length", "toolUse", "error", "aborted", "unknown"],
					fallback: "unknown",
				},
			},
			legacy_properties: [
				"version",
				"os_family",
				"architecture",
				"install_method",
				"execution_mode",
				"session_id",
				"outcome",
				"duration_ms",
				"visible_ttft_ms",
				"first_model_event_ms",
				"model_latency_ms",
				"max_model_latency_ms",
				"model_call_count",
				"turn_count",
				"tool_call_count",
				"tool_error_count",
				"input_tokens",
				"output_tokens",
				"cache_read_tokens",
				"cache_write_tokens",
				"total_tokens",
				"compaction_count",
				"retry_count",
				"provider_category",
				"model_category",
				"error_category",
			],
		},
		"agent session ended": {
			legacy: true,
			required: [
				"version",
				"os_family",
				"architecture",
				"install_method",
				"execution_mode",
				"session_id",
				"duration_ms",
				"prompt_count",
				"run_count",
				"successful_run_count",
				"failed_run_count",
				"aborted_run_count",
				"tool_call_count",
				"compaction_count",
				"model_call_count",
				"input_tokens",
				"output_tokens",
				"cache_read_tokens",
				"cache_write_tokens",
				"total_tokens",
			],
			properties: {
				version: {
					kind: "version",
				},
				os_family: {
					kind: "enum",
					values: [
						"aix",
						"android",
						"darwin",
						"freebsd",
						"haiku",
						"linux",
						"netbsd",
						"openbsd",
						"sunos",
						"win32",
						"cygwin",
						"unknown",
					],
					fallback: "unknown",
				},
				architecture: {
					kind: "enum",
					values: [
						"arm",
						"arm64",
						"ia32",
						"loong64",
						"mips",
						"mipsel",
						"ppc",
						"ppc64",
						"riscv64",
						"s390",
						"s390x",
						"x64",
						"unknown",
					],
					fallback: "unknown",
				},
				install_method: {
					kind: "enum",
					values: ["bun-binary", "homebrew", "npm", "pnpm", "yarn", "bun", "unknown"],
					fallback: "unknown",
				},
				execution_mode: {
					kind: "enum",
					values: ["interactive", "print", "json", "rpc", "acp", "unknown"],
					fallback: "unknown",
				},
				session_id: {
					kind: "uuid",
				},
				duration_ms: {
					kind: "number",
					max: 31536000000,
					integer: true,
					nullable: true,
				},
				prompt_count: {
					kind: "number",
					max: 1000000,
					integer: true,
				},
				run_count: {
					kind: "number",
					max: 1000000,
					integer: true,
				},
				successful_run_count: {
					kind: "number",
					max: 1000000,
					integer: true,
				},
				failed_run_count: {
					kind: "number",
					max: 1000000,
					integer: true,
				},
				aborted_run_count: {
					kind: "number",
					max: 1000000,
					integer: true,
				},
				tool_call_count: {
					kind: "number",
					max: 1000000,
					integer: true,
				},
				compaction_count: {
					kind: "number",
					max: 1000000,
					integer: true,
				},
				model_call_count: {
					kind: "number",
					max: 1000000,
					integer: true,
				},
				input_tokens: {
					kind: "number",
					max: 1000000000000,
					integer: true,
				},
				output_tokens: {
					kind: "number",
					max: 1000000000000,
					integer: true,
				},
				cache_read_tokens: {
					kind: "number",
					max: 1000000000000,
					integer: true,
				},
				cache_write_tokens: {
					kind: "number",
					max: 1000000000000,
					integer: true,
				},
				total_tokens: {
					kind: "number",
					max: 1000000000000,
					integer: true,
				},
				schema_revision: {
					kind: "number",
					max: 10000,
					integer: true,
				},
				build_channel: {
					kind: "enum",
					values: ["release", "prerelease", "development", "unknown"],
					fallback: "unknown",
				},
				workload_origin: {
					kind: "enum",
					values: ["interactive", "automated", "internal", "test", "unknown"],
					fallback: "unknown",
				},
				run_id: {
					kind: "uuid",
				},
				client_session_id: {
					kind: "uuid",
				},
				onboarding_id: {
					kind: "uuid",
				},
				run_index: {
					kind: "number",
					max: 1000000,
					integer: true,
				},
				elapsed_since_onboarding_ms: {
					kind: "number",
					max: 31536000000,
					integer: true,
					nullable: true,
				},
				provider_category: {
					kind: "enum",
					values: [
						"anthropic",
						"openai",
						"google",
						"prime",
						"openrouter",
						"bedrock",
						"vertex",
						"mistral",
						"groq",
						"xai",
						"custom",
						"unknown",
					],
					fallback: "custom",
				},
				model_category: {
					kind: "enum",
					values: [
						"claude",
						"gpt",
						"o1",
						"o3",
						"o4",
						"gemini",
						"glm",
						"kimi",
						"qwen",
						"deepseek",
						"llama",
						"mistral",
						"custom",
						"unknown",
					],
					fallback: "custom",
				},
				terminal_outcome: {
					kind: "enum",
					values: ["success", "error", "cancelled", "shutdown_interrupted", "unknown"],
					fallback: "unknown",
				},
			},
			legacy_properties: [
				"version",
				"os_family",
				"architecture",
				"install_method",
				"execution_mode",
				"session_id",
				"duration_ms",
				"prompt_count",
				"run_count",
				"successful_run_count",
				"failed_run_count",
				"aborted_run_count",
				"tool_call_count",
				"compaction_count",
				"model_call_count",
				"input_tokens",
				"output_tokens",
				"cache_read_tokens",
				"cache_write_tokens",
				"total_tokens",
			],
		},
		"agent run started": {
			legacy: false,
			required: ["version", "os_family", "architecture", "install_method", "execution_mode", "session_id", "run_id"],
			properties: {
				version: {
					kind: "version",
				},
				os_family: {
					kind: "enum",
					values: [
						"aix",
						"android",
						"darwin",
						"freebsd",
						"haiku",
						"linux",
						"netbsd",
						"openbsd",
						"sunos",
						"win32",
						"cygwin",
						"unknown",
					],
					fallback: "unknown",
				},
				architecture: {
					kind: "enum",
					values: [
						"arm",
						"arm64",
						"ia32",
						"loong64",
						"mips",
						"mipsel",
						"ppc",
						"ppc64",
						"riscv64",
						"s390",
						"s390x",
						"x64",
						"unknown",
					],
					fallback: "unknown",
				},
				install_method: {
					kind: "enum",
					values: ["bun-binary", "homebrew", "npm", "pnpm", "yarn", "bun", "unknown"],
					fallback: "unknown",
				},
				execution_mode: {
					kind: "enum",
					values: ["interactive", "print", "json", "rpc", "acp", "unknown"],
					fallback: "unknown",
				},
				schema_revision: {
					kind: "number",
					max: 10000,
					integer: true,
				},
				build_channel: {
					kind: "enum",
					values: ["release", "prerelease", "development", "unknown"],
					fallback: "unknown",
				},
				workload_origin: {
					kind: "enum",
					values: ["interactive", "automated", "internal", "test", "unknown"],
					fallback: "unknown",
				},
				session_id: {
					kind: "uuid",
				},
				run_id: {
					kind: "uuid",
				},
				client_session_id: {
					kind: "uuid",
				},
				onboarding_id: {
					kind: "uuid",
				},
				run_index: {
					kind: "number",
					max: 1000000,
					integer: true,
				},
				elapsed_since_onboarding_ms: {
					kind: "number",
					max: 31536000000,
					integer: true,
					nullable: true,
				},
				provider_category: {
					kind: "enum",
					values: [
						"anthropic",
						"openai",
						"google",
						"prime",
						"openrouter",
						"bedrock",
						"vertex",
						"mistral",
						"groq",
						"xai",
						"custom",
						"unknown",
					],
					fallback: "custom",
				},
				model_category: {
					kind: "enum",
					values: [
						"claude",
						"gpt",
						"o1",
						"o3",
						"o4",
						"gemini",
						"glm",
						"kimi",
						"qwen",
						"deepseek",
						"llama",
						"mistral",
						"custom",
						"unknown",
					],
					fallback: "custom",
				},
				trigger: {
					kind: "enum",
					values: ["prompt", "continuation", "unknown"],
					fallback: "unknown",
				},
			},
		},
		"agent error": {
			legacy: false,
			required: [
				"version",
				"os_family",
				"architecture",
				"install_method",
				"execution_mode",
				"error_id",
				"error_subtype",
			],
			properties: {
				version: {
					kind: "version",
				},
				os_family: {
					kind: "enum",
					values: [
						"aix",
						"android",
						"darwin",
						"freebsd",
						"haiku",
						"linux",
						"netbsd",
						"openbsd",
						"sunos",
						"win32",
						"cygwin",
						"unknown",
					],
					fallback: "unknown",
				},
				architecture: {
					kind: "enum",
					values: [
						"arm",
						"arm64",
						"ia32",
						"loong64",
						"mips",
						"mipsel",
						"ppc",
						"ppc64",
						"riscv64",
						"s390",
						"s390x",
						"x64",
						"unknown",
					],
					fallback: "unknown",
				},
				install_method: {
					kind: "enum",
					values: ["bun-binary", "homebrew", "npm", "pnpm", "yarn", "bun", "unknown"],
					fallback: "unknown",
				},
				execution_mode: {
					kind: "enum",
					values: ["interactive", "print", "json", "rpc", "acp", "unknown"],
					fallback: "unknown",
				},
				schema_revision: {
					kind: "number",
					max: 10000,
					integer: true,
				},
				build_channel: {
					kind: "enum",
					values: ["release", "prerelease", "development", "unknown"],
					fallback: "unknown",
				},
				workload_origin: {
					kind: "enum",
					values: ["interactive", "automated", "internal", "test", "unknown"],
					fallback: "unknown",
				},
				session_id: {
					kind: "uuid",
				},
				run_id: {
					kind: "uuid",
				},
				client_session_id: {
					kind: "uuid",
				},
				onboarding_id: {
					kind: "uuid",
				},
				run_index: {
					kind: "number",
					max: 1000000,
					integer: true,
				},
				elapsed_since_onboarding_ms: {
					kind: "number",
					max: 31536000000,
					integer: true,
					nullable: true,
				},
				provider_category: {
					kind: "enum",
					values: [
						"anthropic",
						"openai",
						"google",
						"prime",
						"openrouter",
						"bedrock",
						"vertex",
						"mistral",
						"groq",
						"xai",
						"custom",
						"unknown",
					],
					fallback: "custom",
				},
				model_category: {
					kind: "enum",
					values: [
						"claude",
						"gpt",
						"o1",
						"o3",
						"o4",
						"gemini",
						"glm",
						"kimi",
						"qwen",
						"deepseek",
						"llama",
						"mistral",
						"custom",
						"unknown",
					],
					fallback: "custom",
				},
				error_id: {
					kind: "uuid",
				},
				error_category: {
					kind: "enum",
					values: [
						"authentication",
						"rate_limit",
						"timeout",
						"context_limit",
						"network",
						"provider_unavailable",
						"other",
					],
					fallback: "other",
					nullable: true,
				},
				error_subtype: {
					kind: "enum",
					values: [
						"credential_missing",
						"credential_invalid",
						"credential_expired",
						"authentication_rejected",
						"permission_denied",
						"model_access_denied",
						"insufficient_balance",
						"quota_exceeded",
						"rate_limited",
						"network_error",
						"timeout",
						"provider_unavailable",
						"refusal",
						"malformed_response",
						"context_limit",
						"configuration_error",
						"filesystem_error",
						"session_unavailable",
						"cancelled",
						"unknown",
					],
					fallback: "unknown",
				},
				error_code: {
					kind: "enum",
					values: [
						"invalid_api_key",
						"invalid_token",
						"invalid_grant",
						"token_expired",
						"expired_token",
						"missing_api_key",
						"authentication_error",
						"unauthorized",
						"permission_error",
						"permission_denied",
						"access_denied",
						"forbidden",
						"model_not_found",
						"model_access_denied",
						"usage_not_included",
						"insufficient_funds",
						"insufficient_balance",
						"insufficient_quota",
						"quota_exceeded",
						"resource_exhausted",
						"rate_limit_error",
						"rate_limit_exceeded",
						"too_many_requests",
						"overloaded_error",
						"server_error",
						"api_error",
						"service_unavailable",
						"refusal",
						"content_filter",
						"safety",
						"malformed_response",
						"context_length_exceeded",
						"context_window_exceeded",
						"ECONNRESET",
						"ECONNREFUSED",
						"EHOSTUNREACH",
						"ENETUNREACH",
						"ENOTFOUND",
						"EAI_AGAIN",
						"EPIPE",
						"ETIMEDOUT",
						"UND_ERR_CONNECT_TIMEOUT",
						"UND_ERR_HEADERS_TIMEOUT",
						"UND_ERR_BODY_TIMEOUT",
						"UND_ERR_SOCKET",
						"ENOENT",
						"EACCES",
						"EPERM",
						"ENOSPC",
						"EMFILE",
						"EROFS",
						"ELOCKED",
						"missing_session_cwd",
						"session_import_file_not_found",
						"session_already_active",
						"session_recovering",
						"unknown",
					],
					fallback: "unknown",
				},
				http_status: {
					kind: "number",
					max: 599,
					integer: true,
					nullable: true,
				},
				classification_source: {
					kind: "enum",
					values: ["structured_reason", "http_status", "typed_error", "reviewed_message", "unknown"],
					fallback: "unknown",
				},
				classifier_revision: {
					kind: "number",
					max: 10000,
					integer: true,
				},
				diagnostic_message: {
					kind: "enum",
					values: [
						"No API key found for [provider].",
						"Provider rejected the supplied credentials.",
						"Provider credentials have expired.",
						"Provider rejected authentication; the underlying reason is unknown.",
						"Provider denied access to the requested resource.",
						"The selected model is not accessible.",
						"The provider reported insufficient balance.",
						"The provider reported an exhausted quota.",
						"Provider rate limit exceeded.",
						"A network connection failed.",
						"The operation timed out.",
						"The provider is temporarily unavailable.",
						"The provider refused the request or blocked the response.",
						"Provider returned a malformed response.",
						"The request exceeded the model context limit.",
						"The application could not load or use its configuration.",
						"A local file operation failed.",
						"The requested session is unavailable.",
						"Request was aborted.",
						"An error occurred; private error details were omitted.",
					],
				},
				component: {
					kind: "enum",
					values: [
						"startup",
						"configuration",
						"authentication",
						"provider",
						"tools",
						"mcp",
						"extensions",
						"daemon",
						"rpc",
						"acp",
						"session",
						"compaction",
						"background",
						"unknown",
					],
					fallback: "unknown",
				},
				operation: {
					kind: "enum",
					values: [
						"startup",
						"load",
						"save",
						"refresh",
						"validate",
						"login",
						"logout",
						"discover",
						"request",
						"stream",
						"execute",
						"connect",
						"attach",
						"parse",
						"compact",
						"retry",
						"shutdown",
						"uncaught_exception",
						"unhandled_rejection",
						"unknown",
					],
					fallback: "unknown",
				},
				stage: {
					kind: "enum",
					values: [
						"startup",
						"configuration",
						"authentication",
						"model_discovery",
						"model_request",
						"model_stream",
						"tool_execution",
						"session_persistence",
						"compaction",
						"background",
						"shutdown",
						"unknown",
					],
					fallback: "unknown",
				},
				retryable: {
					kind: "boolean",
					nullable: true,
				},
				retry_attempt: {
					kind: "number",
					max: 1000000,
					integer: true,
				},
				retry_backoff_ms: {
					kind: "number",
					max: 31536000000,
					integer: true,
					nullable: true,
				},
				consecutive_failure_count: {
					kind: "number",
					max: 1000000,
					integer: true,
				},
				recovery_action: {
					kind: "enum",
					values: [
						"automatic_retry",
						"manual_retry",
						"credentials_updated",
						"provider_changed",
						"model_changed",
						"cancelled",
						"none",
						"unknown",
					],
					fallback: "unknown",
				},
				recovery_outcome: {
					kind: "enum",
					values: ["pending", "success", "failed", "cancelled", "not_observed", "unknown"],
					fallback: "unknown",
				},
			},
		},
		"agent timing": {
			legacy: false,
			required: ["version", "os_family", "architecture", "install_method", "execution_mode", "stage", "duration_ms"],
			properties: {
				version: {
					kind: "version",
				},
				os_family: {
					kind: "enum",
					values: [
						"aix",
						"android",
						"darwin",
						"freebsd",
						"haiku",
						"linux",
						"netbsd",
						"openbsd",
						"sunos",
						"win32",
						"cygwin",
						"unknown",
					],
					fallback: "unknown",
				},
				architecture: {
					kind: "enum",
					values: [
						"arm",
						"arm64",
						"ia32",
						"loong64",
						"mips",
						"mipsel",
						"ppc",
						"ppc64",
						"riscv64",
						"s390",
						"s390x",
						"x64",
						"unknown",
					],
					fallback: "unknown",
				},
				install_method: {
					kind: "enum",
					values: ["bun-binary", "homebrew", "npm", "pnpm", "yarn", "bun", "unknown"],
					fallback: "unknown",
				},
				execution_mode: {
					kind: "enum",
					values: ["interactive", "print", "json", "rpc", "acp", "unknown"],
					fallback: "unknown",
				},
				schema_revision: {
					kind: "number",
					max: 10000,
					integer: true,
				},
				build_channel: {
					kind: "enum",
					values: ["release", "prerelease", "development", "unknown"],
					fallback: "unknown",
				},
				workload_origin: {
					kind: "enum",
					values: ["interactive", "automated", "internal", "test", "unknown"],
					fallback: "unknown",
				},
				session_id: {
					kind: "uuid",
				},
				run_id: {
					kind: "uuid",
				},
				client_session_id: {
					kind: "uuid",
				},
				onboarding_id: {
					kind: "uuid",
				},
				run_index: {
					kind: "number",
					max: 1000000,
					integer: true,
				},
				elapsed_since_onboarding_ms: {
					kind: "number",
					max: 31536000000,
					integer: true,
					nullable: true,
				},
				provider_category: {
					kind: "enum",
					values: [
						"anthropic",
						"openai",
						"google",
						"prime",
						"openrouter",
						"bedrock",
						"vertex",
						"mistral",
						"groq",
						"xai",
						"custom",
						"unknown",
					],
					fallback: "custom",
				},
				model_category: {
					kind: "enum",
					values: [
						"claude",
						"gpt",
						"o1",
						"o3",
						"o4",
						"gemini",
						"glm",
						"kimi",
						"qwen",
						"deepseek",
						"llama",
						"mistral",
						"custom",
						"unknown",
					],
					fallback: "custom",
				},
				stage: {
					kind: "enum",
					values: [
						"first_status",
						"first_model_event",
						"first_reasoning",
						"first_text",
						"tool",
						"retry_wait",
						"compaction",
						"stream_gap",
						"terminal",
						"unknown",
					],
					fallback: "unknown",
				},
				duration_ms: {
					kind: "number",
					max: 31536000000,
					integer: true,
					nullable: true,
				},
				outcome: {
					kind: "enum",
					values: ["success", "error", "cancelled", "shutdown_interrupted", "unknown"],
					fallback: "unknown",
				},
				tool_category: {
					kind: "enum",
					values: [
						"read",
						"write",
						"edit",
						"bash",
						"grep",
						"find",
						"ls",
						"ipython",
						"mcp",
						"extension",
						"custom",
						"unknown",
					],
					fallback: "custom",
				},
			},
		},
		"agent tool summary": {
			legacy: false,
			required: [
				"version",
				"os_family",
				"architecture",
				"install_method",
				"execution_mode",
				"session_id",
				"run_id",
				"tool_category",
				"call_count",
				"failure_count",
			],
			properties: {
				version: {
					kind: "version",
				},
				os_family: {
					kind: "enum",
					values: [
						"aix",
						"android",
						"darwin",
						"freebsd",
						"haiku",
						"linux",
						"netbsd",
						"openbsd",
						"sunos",
						"win32",
						"cygwin",
						"unknown",
					],
					fallback: "unknown",
				},
				architecture: {
					kind: "enum",
					values: [
						"arm",
						"arm64",
						"ia32",
						"loong64",
						"mips",
						"mipsel",
						"ppc",
						"ppc64",
						"riscv64",
						"s390",
						"s390x",
						"x64",
						"unknown",
					],
					fallback: "unknown",
				},
				install_method: {
					kind: "enum",
					values: ["bun-binary", "homebrew", "npm", "pnpm", "yarn", "bun", "unknown"],
					fallback: "unknown",
				},
				execution_mode: {
					kind: "enum",
					values: ["interactive", "print", "json", "rpc", "acp", "unknown"],
					fallback: "unknown",
				},
				schema_revision: {
					kind: "number",
					max: 10000,
					integer: true,
				},
				build_channel: {
					kind: "enum",
					values: ["release", "prerelease", "development", "unknown"],
					fallback: "unknown",
				},
				workload_origin: {
					kind: "enum",
					values: ["interactive", "automated", "internal", "test", "unknown"],
					fallback: "unknown",
				},
				session_id: {
					kind: "uuid",
				},
				run_id: {
					kind: "uuid",
				},
				client_session_id: {
					kind: "uuid",
				},
				onboarding_id: {
					kind: "uuid",
				},
				run_index: {
					kind: "number",
					max: 1000000,
					integer: true,
				},
				elapsed_since_onboarding_ms: {
					kind: "number",
					max: 31536000000,
					integer: true,
					nullable: true,
				},
				provider_category: {
					kind: "enum",
					values: [
						"anthropic",
						"openai",
						"google",
						"prime",
						"openrouter",
						"bedrock",
						"vertex",
						"mistral",
						"groq",
						"xai",
						"custom",
						"unknown",
					],
					fallback: "custom",
				},
				model_category: {
					kind: "enum",
					values: [
						"claude",
						"gpt",
						"o1",
						"o3",
						"o4",
						"gemini",
						"glm",
						"kimi",
						"qwen",
						"deepseek",
						"llama",
						"mistral",
						"custom",
						"unknown",
					],
					fallback: "custom",
				},
				tool_category: {
					kind: "enum",
					values: [
						"read",
						"write",
						"edit",
						"bash",
						"grep",
						"find",
						"ls",
						"ipython",
						"mcp",
						"extension",
						"custom",
						"unknown",
					],
					fallback: "custom",
				},
				call_count: {
					kind: "number",
					max: 1000000,
					integer: true,
				},
				failure_count: {
					kind: "number",
					max: 1000000,
					integer: true,
				},
				duration_ms: {
					kind: "number",
					max: 31536000000,
					integer: true,
					nullable: true,
				},
				recovered_count: {
					kind: "number",
					max: 1000000,
					integer: true,
				},
			},
		},
		"onboarding stage": {
			legacy: false,
			required: [
				"version",
				"os_family",
				"architecture",
				"install_method",
				"execution_mode",
				"onboarding_id",
				"stage",
				"outcome",
			],
			properties: {
				version: {
					kind: "version",
				},
				os_family: {
					kind: "enum",
					values: [
						"aix",
						"android",
						"darwin",
						"freebsd",
						"haiku",
						"linux",
						"netbsd",
						"openbsd",
						"sunos",
						"win32",
						"cygwin",
						"unknown",
					],
					fallback: "unknown",
				},
				architecture: {
					kind: "enum",
					values: [
						"arm",
						"arm64",
						"ia32",
						"loong64",
						"mips",
						"mipsel",
						"ppc",
						"ppc64",
						"riscv64",
						"s390",
						"s390x",
						"x64",
						"unknown",
					],
					fallback: "unknown",
				},
				install_method: {
					kind: "enum",
					values: ["bun-binary", "homebrew", "npm", "pnpm", "yarn", "bun", "unknown"],
					fallback: "unknown",
				},
				execution_mode: {
					kind: "enum",
					values: ["interactive", "print", "json", "rpc", "acp", "unknown"],
					fallback: "unknown",
				},
				schema_revision: {
					kind: "number",
					max: 10000,
					integer: true,
				},
				build_channel: {
					kind: "enum",
					values: ["release", "prerelease", "development", "unknown"],
					fallback: "unknown",
				},
				workload_origin: {
					kind: "enum",
					values: ["interactive", "automated", "internal", "test", "unknown"],
					fallback: "unknown",
				},
				session_id: {
					kind: "uuid",
				},
				run_id: {
					kind: "uuid",
				},
				client_session_id: {
					kind: "uuid",
				},
				onboarding_id: {
					kind: "uuid",
				},
				run_index: {
					kind: "number",
					max: 1000000,
					integer: true,
				},
				elapsed_since_onboarding_ms: {
					kind: "number",
					max: 31536000000,
					integer: true,
					nullable: true,
				},
				provider_category: {
					kind: "enum",
					values: [
						"anthropic",
						"openai",
						"google",
						"prime",
						"openrouter",
						"bedrock",
						"vertex",
						"mistral",
						"groq",
						"xai",
						"custom",
						"unknown",
					],
					fallback: "custom",
				},
				model_category: {
					kind: "enum",
					values: [
						"claude",
						"gpt",
						"o1",
						"o3",
						"o4",
						"gemini",
						"glm",
						"kimi",
						"qwen",
						"deepseek",
						"llama",
						"mistral",
						"custom",
						"unknown",
					],
					fallback: "custom",
				},
				stage: {
					kind: "enum",
					values: [
						"entry",
						"provider_selection",
						"credential_discovery",
						"credential_validation",
						"model_access",
						"ready",
						"exit",
					],
				},
				outcome: {
					kind: "enum",
					values: [
						"initiated",
						"completed",
						"failed",
						"canceled",
						"skipped",
						"configured",
						"unavailable",
						"provider_switched",
					],
				},
				duration_ms: {
					kind: "number",
					max: 31536000000,
					integer: true,
					nullable: true,
				},
				auth_category: {
					kind: "enum",
					values: [
						"oauth",
						"api_key",
						"runtime_api_key",
						"environment",
						"prime_cli",
						"models_json",
						"fallback",
						"stale",
						"stored",
						"none",
					],
					fallback: "none",
				},
				acquisition_method: {
					kind: "enum",
					values: [
						"existing_configuration",
						"prime_browser",
						"prime_key_entry",
						"oauth",
						"api_key_entry",
						"external_credentials",
						"unknown",
					],
					fallback: "unknown",
				},
				validation_scope: {
					kind: "enum",
					values: ["configuration", "identity_scope", "selected_context", "inference", "unchecked"],
					fallback: "unchecked",
				},
				entry_reason: {
					kind: "enum",
					values: ["first_setup", "existing_configuration", "previously_shown", "reentered"],
				},
				timing_scope: {
					kind: "enum",
					values: ["elapsed_including_user_wait", "system_work"],
				},
			},
		},
		"agent feature outcome": {
			legacy: false,
			required: [
				"version",
				"os_family",
				"architecture",
				"install_method",
				"execution_mode",
				"feature_id",
				"feature_name",
				"outcome",
			],
			properties: {
				version: {
					kind: "version",
				},
				os_family: {
					kind: "enum",
					values: [
						"aix",
						"android",
						"darwin",
						"freebsd",
						"haiku",
						"linux",
						"netbsd",
						"openbsd",
						"sunos",
						"win32",
						"cygwin",
						"unknown",
					],
					fallback: "unknown",
				},
				architecture: {
					kind: "enum",
					values: [
						"arm",
						"arm64",
						"ia32",
						"loong64",
						"mips",
						"mipsel",
						"ppc",
						"ppc64",
						"riscv64",
						"s390",
						"s390x",
						"x64",
						"unknown",
					],
					fallback: "unknown",
				},
				install_method: {
					kind: "enum",
					values: ["bun-binary", "homebrew", "npm", "pnpm", "yarn", "bun", "unknown"],
					fallback: "unknown",
				},
				execution_mode: {
					kind: "enum",
					values: ["interactive", "print", "json", "rpc", "acp", "unknown"],
					fallback: "unknown",
				},
				schema_revision: {
					kind: "number",
					max: 10000,
					integer: true,
				},
				build_channel: {
					kind: "enum",
					values: ["release", "prerelease", "development", "unknown"],
					fallback: "unknown",
				},
				workload_origin: {
					kind: "enum",
					values: ["interactive", "automated", "internal", "test", "unknown"],
					fallback: "unknown",
				},
				session_id: {
					kind: "uuid",
				},
				run_id: {
					kind: "uuid",
				},
				client_session_id: {
					kind: "uuid",
				},
				onboarding_id: {
					kind: "uuid",
				},
				run_index: {
					kind: "number",
					max: 1000000,
					integer: true,
				},
				elapsed_since_onboarding_ms: {
					kind: "number",
					max: 31536000000,
					integer: true,
					nullable: true,
				},
				provider_category: {
					kind: "enum",
					values: [
						"anthropic",
						"openai",
						"google",
						"prime",
						"openrouter",
						"bedrock",
						"vertex",
						"mistral",
						"groq",
						"xai",
						"custom",
						"unknown",
					],
					fallback: "custom",
				},
				model_category: {
					kind: "enum",
					values: [
						"claude",
						"gpt",
						"o1",
						"o3",
						"o4",
						"gemini",
						"glm",
						"kimi",
						"qwen",
						"deepseek",
						"llama",
						"mistral",
						"custom",
						"unknown",
					],
					fallback: "custom",
				},
				feature_id: {
					kind: "uuid",
				},
				feature_name: {
					kind: "enum",
					values: [
						"model",
						"login",
						"logout",
						"effort",
						"goal",
						"new",
						"resume",
						"fork",
						"clone",
						"tree",
						"feedback",
					],
				},
				outcome: {
					kind: "enum",
					values: ["initiated", "completed", "failed", "canceled", "unavailable"],
				},
				duration_ms: {
					kind: "number",
					max: 31536000000,
					integer: true,
					nullable: true,
				},
				configuration_choice: {
					kind: "enum",
					values: [
						"off",
						"minimal",
						"low",
						"medium",
						"high",
						"xhigh",
						"max",
						"create",
						"status",
						"pause",
						"resume",
						"clear",
						"unknown",
					],
					fallback: "unknown",
				},
				feedback: {
					kind: "enum",
					values: ["helpful", "partly_helpful", "not_helpful"],
				},
				previous_success: {
					kind: "boolean",
				},
			},
		},
		"agent startup stage": {
			legacy: false,
			required: [
				"version",
				"os_family",
				"architecture",
				"install_method",
				"execution_mode",
				"stage",
				"outcome",
				"duration_ms",
			],
			properties: {
				version: {
					kind: "version",
				},
				os_family: {
					kind: "enum",
					values: [
						"aix",
						"android",
						"darwin",
						"freebsd",
						"haiku",
						"linux",
						"netbsd",
						"openbsd",
						"sunos",
						"win32",
						"cygwin",
						"unknown",
					],
					fallback: "unknown",
				},
				architecture: {
					kind: "enum",
					values: [
						"arm",
						"arm64",
						"ia32",
						"loong64",
						"mips",
						"mipsel",
						"ppc",
						"ppc64",
						"riscv64",
						"s390",
						"s390x",
						"x64",
						"unknown",
					],
					fallback: "unknown",
				},
				install_method: {
					kind: "enum",
					values: ["bun-binary", "homebrew", "npm", "pnpm", "yarn", "bun", "unknown"],
					fallback: "unknown",
				},
				execution_mode: {
					kind: "enum",
					values: ["interactive", "print", "json", "rpc", "acp", "unknown"],
					fallback: "unknown",
				},
				schema_revision: {
					kind: "number",
					max: 10000,
					integer: true,
				},
				build_channel: {
					kind: "enum",
					values: ["release", "prerelease", "development", "unknown"],
					fallback: "unknown",
				},
				workload_origin: {
					kind: "enum",
					values: ["interactive", "automated", "internal", "test", "unknown"],
					fallback: "unknown",
				},
				session_id: {
					kind: "uuid",
				},
				run_id: {
					kind: "uuid",
				},
				client_session_id: {
					kind: "uuid",
				},
				onboarding_id: {
					kind: "uuid",
				},
				run_index: {
					kind: "number",
					max: 1000000,
					integer: true,
				},
				elapsed_since_onboarding_ms: {
					kind: "number",
					max: 31536000000,
					integer: true,
					nullable: true,
				},
				provider_category: {
					kind: "enum",
					values: [
						"anthropic",
						"openai",
						"google",
						"prime",
						"openrouter",
						"bedrock",
						"vertex",
						"mistral",
						"groq",
						"xai",
						"custom",
						"unknown",
					],
					fallback: "custom",
				},
				model_category: {
					kind: "enum",
					values: [
						"claude",
						"gpt",
						"o1",
						"o3",
						"o4",
						"gemini",
						"glm",
						"kimi",
						"qwen",
						"deepseek",
						"llama",
						"mistral",
						"custom",
						"unknown",
					],
					fallback: "custom",
				},
				stage: {
					kind: "enum",
					values: [
						"ui_ready",
						"session_attach",
						"configuration_load",
						"credential_validation",
						"session_ui_rebind",
					],
				},
				outcome: {
					kind: "enum",
					values: ["completed", "failed"],
				},
				duration_ms: {
					kind: "number",
					max: 31536000000,
					integer: true,
					nullable: true,
				},
				startup_kind: {
					kind: "enum",
					values: ["cold", "warm_attach", "resumed", "unknown"],
					fallback: "unknown",
				},
				timing_scope: {
					kind: "enum",
					values: ["system_work", "elapsed_including_user_wait"],
				},
			},
		},
	},
	diagnostic_messages: {
		credential_missing: "No API key found for [provider].",
		credential_invalid: "Provider rejected the supplied credentials.",
		credential_expired: "Provider credentials have expired.",
		authentication_rejected: "Provider rejected authentication; the underlying reason is unknown.",
		permission_denied: "Provider denied access to the requested resource.",
		model_access_denied: "The selected model is not accessible.",
		insufficient_balance: "The provider reported insufficient balance.",
		quota_exceeded: "The provider reported an exhausted quota.",
		rate_limited: "Provider rate limit exceeded.",
		network_error: "A network connection failed.",
		timeout: "The operation timed out.",
		provider_unavailable: "The provider is temporarily unavailable.",
		refusal: "The provider refused the request or blocked the response.",
		malformed_response: "Provider returned a malformed response.",
		context_limit: "The request exceeded the model context limit.",
		configuration_error: "The application could not load or use its configuration.",
		filesystem_error: "A local file operation failed.",
		session_unavailable: "The requested session is unavailable.",
		cancelled: "Request was aborted.",
		unknown: "An error occurred; private error details were omitted.",
	},
};
