export const TELEMETRY_ERROR_MESSAGE_POLICY_REVISION = 1;

// Every value is fixed application text or a system description without runtime values.
export const TELEMETRY_SAFE_ERROR_MESSAGES = {
	auth_storage_lock_failed: "Failed to acquire auth storage lock",
	auth_storage_lock_compromised: "Auth storage lock was compromised",
	prime_cli_disabled: "Prime CLI config is not enabled",
	login_cancelled: "Login cancelled",
	prime_request_timeout: "Prime Inference request timed out",
	prime_teams_invalid_response: "Prime teams returned an invalid response",
	prime_teams_missing_data: "Prime teams response missing team data",
	prime_challenge_invalid_response: "Prime login challenge returned an invalid response",
	prime_challenge_missing_fields: "Prime login challenge response missing required fields",
	prime_challenge_expired: "Prime login challenge expired",
	prime_login_status_invalid_response: "Prime login status returned an invalid response",
	prime_whoami_invalid_response: "Prime whoami returned an invalid response",
	prime_whoami_missing_user: "Prime whoami response missing user data",
	prime_permission_scope_missing: "Prime token is missing permission scope data",
	prime_inference_permission_missing: "Prime token is missing inference permissions",
	prime_inference_write_permission_missing: "Prime token does not have inference write permission",
	prime_trace_permission_missing: "Prime token is missing agent trace permissions",
	prime_trace_write_permission_missing: "Prime token does not have agent trace write permission",
	request_aborted: "Request was aborted",
	provider_refusal: "Model refused to respond",
	provider_safety: "Response blocked by provider safety filters",
	provider_overloaded: "Provider overloaded",
	provider_rate_limit: "Provider rate limit exceeded",
	provider_server_error: "Provider server error",
	provider_authentication: "Provider authentication failed",
	provider_permission: "Provider denied access to the requested resource",
	provider_invalid_request: "Provider rejected the request",
	provider_malformed_response: "Provider returned a malformed response",
	provider_stream_failure: "Provider stream failed",
	system_file_missing: "A required file or directory was not found.",
	system_permission_denied: "The operating system denied access to a resource.",
	system_operation_not_permitted: "The operating system did not permit the operation.",
	system_no_space: "The device has no space left.",
	system_too_many_files: "The process has too many open files.",
	system_file_table_full: "The system has too many open files.",
	system_read_only: "The file system is read-only.",
	system_locked: "The resource is locked.",
	system_already_exists: "The file or directory already exists.",
	system_directory_not_empty: "The directory is not empty.",
	system_resource_busy: "The resource is busy.",
	system_not_directory: "A path component is not a directory.",
	system_is_directory: "The operation requires a file but received a directory.",
	system_io_error: "A system input or output operation failed.",
	system_address_in_use: "The network address is already in use.",
	system_address_unavailable: "The requested network address is unavailable.",
	system_connection_reset: "The network connection was reset.",
	system_connection_refused: "The network connection was refused.",
	system_connection_aborted: "The network connection was aborted.",
	system_host_unreachable: "The network host is unreachable.",
	system_network_unreachable: "The network is unreachable.",
	system_host_not_found: "The network host could not be resolved.",
	system_dns_retry: "Name resolution failed temporarily.",
	system_broken_pipe: "The connection was closed while writing.",
	system_timeout: "The system operation timed out.",
	system_socket_error: "The network socket failed.",
	system_session_cwd_missing: "The stored session working directory does not exist.",
	system_session_import_missing: "The session import file was not found.",
	system_session_active: "The session is already active in another process.",
	system_session_recovering: "The session is recovering; retry shortly.",
} as const;

export type TelemetrySafeErrorMessageId = keyof typeof TELEMETRY_SAFE_ERROR_MESSAGES;

export const TELEMETRY_SYSTEM_ERROR_MESSAGE_IDS = {
	ENOENT: "system_file_missing",
	EACCES: "system_permission_denied",
	EPERM: "system_operation_not_permitted",
	ENOSPC: "system_no_space",
	EMFILE: "system_too_many_files",
	ENFILE: "system_file_table_full",
	EROFS: "system_read_only",
	ELOCKED: "system_locked",
	EEXIST: "system_already_exists",
	ENOTEMPTY: "system_directory_not_empty",
	EBUSY: "system_resource_busy",
	ENOTDIR: "system_not_directory",
	EISDIR: "system_is_directory",
	EIO: "system_io_error",
	EADDRINUSE: "system_address_in_use",
	EADDRNOTAVAIL: "system_address_unavailable",
	ECONNRESET: "system_connection_reset",
	ECONNREFUSED: "system_connection_refused",
	ECONNABORTED: "system_connection_aborted",
	EHOSTUNREACH: "system_host_unreachable",
	ENETUNREACH: "system_network_unreachable",
	ENOTFOUND: "system_host_not_found",
	EAI_AGAIN: "system_dns_retry",
	EPIPE: "system_broken_pipe",
	ETIMEDOUT: "system_timeout",
	UND_ERR_CONNECT_TIMEOUT: "system_timeout",
	UND_ERR_HEADERS_TIMEOUT: "system_timeout",
	UND_ERR_BODY_TIMEOUT: "system_timeout",
	UND_ERR_SOCKET: "system_socket_error",
	missing_session_cwd: "system_session_cwd_missing",
	session_import_file_not_found: "system_session_import_missing",
	session_already_active: "system_session_active",
	session_recovering: "system_session_recovering",
} as const satisfies Record<string, TelemetrySafeErrorMessageId>;

export const TELEMETRY_SAFE_ERROR_CODES = [
	"invalid_api_key",
	"invalid_token",
	"invalid_grant",
	"token_expired",
	"expired_token",
	"missing_api_key",
	"authentication_error",
	"unauthorized",
	"permission_error",
	"permission_denied",
	"access_denied",
	"forbidden",
	"model_not_found",
	"model_access_denied",
	"usage_not_included",
	"insufficient_funds",
	"insufficient_balance",
	"insufficient_quota",
	"quota_exceeded",
	"resource_exhausted",
	"rate_limit_error",
	"rate_limit_exceeded",
	"too_many_requests",
	"overloaded_error",
	"server_error",
	"api_error",
	"service_unavailable",
	"refusal",
	"content_filter",
	"safety",
	"malformed_response",
	"context_length_exceeded",
	"context_window_exceeded",
	...Object.keys(TELEMETRY_SYSTEM_ERROR_MESSAGE_IDS),
	"daemon_supervisor_already_running",
	"supervisor_generation_stale",
	"daemon_shutdown_in_progress",
	"supervisor_recovery_cancelled",
	"command_result_uncertain",
	"unknown",
] as const;

export const TELEMETRY_SAFE_ERROR_SIGNALS = [
	"SIGHUP",
	"SIGINT",
	"SIGQUIT",
	"SIGILL",
	"SIGTRAP",
	"SIGABRT",
	"SIGIOT",
	"SIGBUS",
	"SIGFPE",
	"SIGKILL",
	"SIGUSR1",
	"SIGSEGV",
	"SIGUSR2",
	"SIGPIPE",
	"SIGALRM",
	"SIGTERM",
	"SIGCHLD",
	"SIGCONT",
	"SIGSTOP",
	"SIGTSTP",
	"SIGTTIN",
	"SIGTTOU",
	"SIGURG",
	"SIGXCPU",
	"SIGXFSZ",
	"SIGVTALRM",
	"SIGPROF",
	"SIGWINCH",
	"SIGIO",
	"SIGPOLL",
	"SIGPWR",
	"SIGSYS",
	"SIGBREAK",
] as const;

export function getTelemetrySafeErrorMessage(id: unknown): string | undefined {
	return typeof id === "string" && Object.hasOwn(TELEMETRY_SAFE_ERROR_MESSAGES, id)
		? TELEMETRY_SAFE_ERROR_MESSAGES[id as TelemetrySafeErrorMessageId]
		: undefined;
}

export function findTelemetrySafeErrorMessageId(value: string): TelemetrySafeErrorMessageId | undefined {
	return Object.entries(TELEMETRY_SAFE_ERROR_MESSAGES).find(([, message]) => message === value)?.[0] as
		| TelemetrySafeErrorMessageId
		| undefined;
}

export function getTelemetrySafeErrorMessageSource(
	id: TelemetrySafeErrorMessageId,
): "reviewed_literal" | "system_template" {
	return id.startsWith("system_") ? "system_template" : "reviewed_literal";
}
